// project lists to map and render

const mainProjects = [
  {
    title: 'Dietry',
    summary: 'A web application (+ mobile interface) where users can add foods, create unique meals, track their daily diet, weight, and macronutritions.',
    features: [
      'Create an account to keep track of progess.',
      'Create/update profile to calculate BMR macronutrition.',
      'Add/update custom foods or fetch from the USDA API',
      'Add/update unique meals to add to daily diet',
      'Add and track weight over time',
      'View/track progress over specific date ranges in dynamic graphs.',
      'Convert weight and energy units for easy tracking',
      'Pick different themes for a personalized interface'
    ],
    icon: 'BiLeaf',
    thumbnail: 'dietry/login.png',
    images: [
      'dietry/login.png',
      'dietry/homepage.png',
      'dietry/profile.png',
      'dietry/search.png',
      'dietry/foods.png',
      'dietry/meals.png',
      'dietry/modifyMeal.png',
      'dietry/calendar.png',
      'dietry/progress.png',
      'dietry/signup.png',
      'dietry/theme1.png',
      'dietry/theme2.png',
      'dietry/mobileLogin.png',
      'dietry/mobileFoods.png',
      'dietry/mobileViewFood.png',
      'dietry/mobileModifyFood.png',
      'dietry/mobileMeals.png',
      'dietry/mobileModifyMeal.png',
      'dietry/mobileCalendar.png',
      'dietry/mobileProfile.png',
      'dietry/mobileMenu.png',
      'dietry/mobileConverter.png',
    ],
    video: '',
    repository: 'https://github.com/fannychen623/diet-planner',
  },
  {
    title: 'Step It Up',
    summary: 'A web application where users can create and check off completing their unique workout routines. Users can post and share their progress.',
    features: [
      'Create an account to keep track of progess.',
      'Create/update profile to calculate maintanence calorie.',
      'Create/remove custom workout routines.',
      'Add/update daily routine(s), weight, and calorie on a calendar.',
      'View/track progress over specific date ranges.',
      'Share progress, routine(s), and/or thoughts in posts.',
      'View, like, and comment on other user\'s posts.',
      'Browse through a list of Spotify workout playlists.'
    ],
    icon: 'BiDumbbell',
    thumbnail: 'stepItUp/main.png',
    images: [
      'stepItUp/homePage.png',
      'stepItUp/calendarPage.png',
      'stepItUp/trackerPage.png',
      'stepItUp/myRoutinesPage.png',
      'stepItUp/blogPage.png',
      'stepItUp/playlistsPage.png',
      'stepItUp/profilePage.png',
      'stepItUp/login.png',
      'stepItUp/signup.png',
      'stepItUp/addProfile.png',
      'stepItUp/createRoutine1.png',
      'stepItUp/createRoutine2.png',
      'stepItUp/createPost.png',
    ],
    video: 'https://drive.google.com/file/d/1yqn8I9oVM2WCcu3dixPyfWu7O5IIUvU9/view?usp=sharing',
    repository: 'https://github.com/analisegiobbi3/Step_IT_Up',
  },
  {
    title: 'Share A Byte',
    summary: 'A web application where users can create, share, and favorite unique recipes. Use OpenAI to make creating unique recipes simple and fun.',
    features: [
      'Create and account for personal record keeping',
      'View/navigate through recipes on an interactive recipe book style catalog page',
      'View/search recipes based on keyterms on a search page.',
      'Navigate to a specific recipe to view details and like/favorite the recipe.',
      'Create your own recipes and upload a corresponding image or select from a default list of icons.',
      'Used AI to create a random recipe from an input list of ingredients',
      'View/update/remove your own recipes',
      'View/remove from a list of your favorite recipes',
    ],
    icon: 'BiRestaurant',
    thumbnail: 'shareAByte/main.png',
    images: [
      'shareAByte/main.png',
      'shareAByte/catalogPage.png',
      'shareAByte/searchPage.png',
      'shareAByte/myRecipePage.png',
      'shareAByte/myFavoritesPage.png',
      'shareAByte/recipePage.png',
      'shareAByte/login.png',
      'shareAByte/signup.png',
      'shareAByte/newRecipe.png',
      'shareAByte/randomRecipe.png',
    ],
    video: 'https://drive.google.com/file/d/1vQD8mk_XY0VCUSZ8B1Cpv1rNpRRtxcTD/view?usp=sharing',
    repository: 'https://github.com/fannychen623/Project-02-Recipe-Book',
  },
  {
    title: 'GIF Me MARVEL',
    summary: 'A web application where users can lookup, browse, and favorite their favorite MARVEL characters an related GIFs.',
    features: [
      'Search for specific MARVEL characters.',
      'Navigate to a characters official MARVEL page.',
      'Favorite and Unfavorite GIFs.',
      'Re-access favorite GIFs that are stored in local storage.',
    ],
    icon: 'BiRocket',
    thumbnail: 'gifMeMarvel/main.png',
    images: [
      'gifMeMarvel/main.png',
      'gifMeMarvel/characterPage.png',
      'gifMeMarvel/favoriteGif.png',
      'gifMeMarvel/myFavoritesPage.png',
      'gifMeMarvel/removeFavorite.png',
      'gifMeMarvel/loadingPage1.png',
      'gifMeMarvel/loadingPage2.png',
    ],
    video: 'https://drive.google.com/file/d/1GKSDmhku0hjmfoFpDMUrHUDjFhWyeK-g/view?usp=sharing',
    repository: 'https://github.com/mshaari/gif-me-marvel',
  },
];

export default mainProjects;
